### PR TITLE
Add function to cancel compress.

### PR DESCRIPTION
**Pull request by nayaku**
I want to cancel when compressing, so I add a function to cancel.

### CODE REVIEW

**Comment by ied206** [comment]
You can call `Dispose()` or `Close()` anytime to cancel compression already.
Besides, your `CancelCompress()` implementation is a copied version of the current `Dispose()` code.
The stream instance being unusable after calling `CancelCompression()` is the exact behavior of the disposable pattern.

Would you happen to have any particular reason besides adding a new method?

**Comment by ied206** [comment]
If you want to keep your base stream alive even if the `XZStream` was disposed of, you can set the `XZCompressOptions.LeaveOpen` property to true. 

If you need any examples, look through the `Benchmark` project and its `CompBench.cs` implementation.

**Comment by nayaku** [comment]
I need to a function to stop immediately, not to flush buffer to disk.

**Comment by nayaku** [comment]
I really lack consideration in this part, I don't know how to do it. But I needed it to stop immediately because the `flush` method took up too much time. And I no longer need this data.

**Comment by ied206** [comment]
> But I needed it to stop immediately because the flush method took up too much time. And I no longer need this data.

My stream implementations follow the conventions of [.NET official zlib streams interface](https://learn.microsoft.com/ko-kr/dotnet/api/system.io.compression.deflatestream?view=net-7.0). They do not implement an immediate stop feature, and no other compression C# implementations do in my knowledge. My guess is that in most cases one can just `Close()` to abort, it won't take any time. But I also understand your case, because the choice of `liblzma` to save space by using a lot of time makes it notable.

I will implement the abort feature myself. The current PR implementation needs some adjustments.

1. Active development happens on `develop` branch. A rebase would be needed.
    - I have been reorganizing the structure of the internal xz-related streams.
1. Rename `CancelCompress()` to  `Abort()` and make it work on decompress mode, even if it does not do anything.
    - Users will anticipate decompression would be also abortable. 

A new release would take some days.

**Comment by nayaku** [comment]
This sounds great!!! Thank you so much! I am looking forward to the next release.

**Comment by ied206** [comment]
[Joveler.Compression.XZ v4.3.0](https://www.nuget.org/packages/Joveler.Compression.XZ/4.3.0) is now live on NuGet.

**Pull request closed without merging**
